import { Router } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import employeesRouter from "./employees.js";
import attendanceRouter from "./attendance.js";
import payrollRouter from "./payroll.js";
import { validateRequest } from "../lib/validation.js";
import payrollExtrasRouter from "./payroll_extras.js";
import leavesRouter from "./leaves.js";
import customersRouter from "./customers.js";
import vendorsRouter from "./vendors.js";
import projectsRouter from "./projects.js";
import purchaseOrdersRouter from "./purchase_orders.js";
import inventoryRouter from "./inventory.js";
import expensesRouter from "./expenses.js";
import revenueRouter from "./revenue.js";
import invoicesRouter from "./invoices.js";
import documentsRouter from "./documents.js";
import dashboardRouter from "./dashboard.js";
import notificationsRouter from "./notifications.js";
import auditLogsRouter from "./audit_logs.js";
import activityLogsRouter from "./activity_logs.js";
import systemLogsRouter from "./system_logs.js";
import rolesRouter from "./roles.js";
import settingsRouter from "./settings.js";
import remindersRouter from "./reminders.js";
import reportsRouter from "./reports.js";
import workAllocationRouter from "./work_allocation.js";
import importRouter from "./import.js";
import ledgerRouter from "./ledger.js";

const router = Router();

router.use(validateRequest as any);
router.use(healthRouter as any);
router.use(authRouter as any);
router.use(importRouter as any);
router.use(employeesRouter as any);
router.use(attendanceRouter as any);
router.use(payrollRouter as any);
router.use(payrollExtrasRouter as any);
router.use(leavesRouter as any);
router.use(customersRouter as any);
router.use(vendorsRouter as any);
router.use(projectsRouter as any);
router.use(purchaseOrdersRouter as any);
router.use(inventoryRouter as any);
router.use(expensesRouter as any);
router.use(revenueRouter as any);
router.use(invoicesRouter as any);
router.use(documentsRouter as any);
router.use(dashboardRouter as any);
router.use(notificationsRouter as any);
router.use(auditLogsRouter as any);
router.use(activityLogsRouter as any);
router.use(systemLogsRouter as any);
router.use(rolesRouter as any);
router.use(settingsRouter as any);
router.use(remindersRouter as any);
router.use(reportsRouter as any);
router.use(workAllocationRouter as any);
router.use(ledgerRouter as any);

export default router;
