import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth.js";
import employeesRouter from "./employees.js";
import attendanceRouter from "./attendance.js";
import payrollRouter from "./payroll.js";
import { validateRequest } from "../lib/validation.js";
import payrollExtrasRouter from "./payroll_extras.js";
import leavesRouter from "./leaves.js";
import customersRouter from "./customers.js";
import vendorsRouter from "./vendors.js";
import projectsRouter from "./projects.js";
import purchaseOrdersRouter from "./purchase_orders.js";
import inventoryRouter from "./inventory.js";
import expensesRouter from "./expenses.js";
import revenueRouter from "./revenue.js";
import invoicesRouter from "./invoices.js";
import documentsRouter from "./documents.js";
import dashboardRouter from "./dashboard.js";
import notificationsRouter from "./notifications.js";
import auditLogsRouter from "./audit_logs.js";
import rolesRouter from "./roles.js";
import settingsRouter from "./settings.js";
import remindersRouter from "./reminders.js";
import reportsRouter from "./reports.js";
import workAllocationRouter from "./work_allocation.js";
import importRouter from "./import.js";
import ledgerRouter from "./ledger.js";

const router: IRouter = Router();

router.use(validateRequest);
router.use(healthRouter);
router.use(authRouter);
router.use(importRouter);
router.use(employeesRouter);
router.use(attendanceRouter);
router.use(payrollRouter);
router.use(payrollExtrasRouter);
router.use(leavesRouter);
router.use(customersRouter);
router.use(vendorsRouter);
router.use(projectsRouter);
router.use(purchaseOrdersRouter);
router.use(inventoryRouter);
router.use(expensesRouter);
router.use(revenueRouter);
router.use(invoicesRouter);
router.use(documentsRouter);
router.use(dashboardRouter);
router.use(notificationsRouter);
router.use(auditLogsRouter);
router.use(rolesRouter);
router.use(settingsRouter);
router.use(remindersRouter);
router.use(reportsRouter);
router.use(workAllocationRouter);
router.use(ledgerRouter);

export default router;
